### ISSUE TITLE
Need more clarification

### ISSUE THREAD

**Issue by ph4br1c3** [THEBIG-1/Destiny-2-FW#1]
Hi,

Would you be kind to give me more clarification about the procedure?

everything is working correctly but i need to know more about the procedure in practice.
- What the timing when to withdraw the other team?
- is it possible to withdraw always the same team?

Thank you

**Comment by THEBIG-1** [comment]
- It has to do when you start searching and who first. Ok be changing this to private I only have this public for someone else to get access.  But if you have the rest of it working you should be able to figure it out.

**Comment by ph4br1c3** [comment]
yeah everything is working perfectly, i just can not really catch the timing when to withdraw the other team. Probably need more practice. Thank you for your answer.

**Comment by Melvinbrooks** [comment]
@ph4br1c3 Hey brother, 
do you mind helping me? I'm new to coding and would like to get this working. it'll be a great help. thanks for reading

**Comment by THEBIG-1** [comment]
Same as my previous comment. I did not mean for this version to be available to others, if you look you should be able to find it somewhere else.

**Comment by ph4br1c3** [comment]
@Melvinbrooks
It's just a fork of this repository https://github.com/fswdevl/Destiny-2-SDR-Matchmaking-Firewall
Open an issue and describe your problem...

**Comment by THEBIG-1** [comment]
Yup and even that's a changed one from original. Good luck on it. It's not impossible to figure out. I should really just remember to remove this but can't get it done off my cell.

**Comment by Melvinbrooks** [comment]
thank you both for your help!
